# Nginx — Sapabidan (salin ke /etc/nginx/sites-available/sapabidan)
# sudo ln -s /etc/nginx/sites-available/sapabidan /etc/nginx/sites-enabled/
# sudo certbot --nginx -d sapabidan.labvr.unusa.ac.id

server {
    listen 80;
    server_name sapabidan.labvr.unusa.ac.id;

    location / {
        proxy_pass http://127.0.0.1:3031;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache_bypass $http_upgrade;
    }
}
