-- Akun login DARSI terhubung ke master pasien SIMRS (pasienkonsul.b_ms_pasien)
-- Jalankan: PGPASSWORD=PASSWORD psql -h localhost -U postgres -d hospital_cs -f scripts/migrate-patient-accounts.sql

CREATE TABLE IF NOT EXISTS pasienkonsul.darsi_patient_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint NOT NULL REFERENCES pasienkonsul.b_ms_pasien(id) ON DELETE CASCADE,
  email varchar(100) NOT NULL,
  username varchar(50) NOT NULL,
  password_hash varchar(255) NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT darsi_patient_accounts_email_key UNIQUE (email),
  CONSTRAINT darsi_patient_accounts_username_key UNIQUE (username),
  CONSTRAINT darsi_patient_accounts_patient_id_key UNIQUE (patient_id)
);

CREATE INDEX IF NOT EXISTS idx_darsi_patient_accounts_email_lower
  ON pasienkonsul.darsi_patient_accounts (lower(email));

CREATE INDEX IF NOT EXISTS idx_darsi_patient_accounts_username_lower
  ON pasienkonsul.darsi_patient_accounts (lower(username));
